; ============================================================================
; 2026 Assembler - Pre-processor Success / First Pass Failure Test
; File: preproc_ok_first_pass_fail.as
;
; PURPOSE:
; 1. All macro definitions and calls are 100% valid.
;    -> This ensures the pre-processor stage succeeds and generates a .am file.
; 2. Contains syntax and semantic errors that are only caught in the First Pass.
;    -> This ensures first_pass() 
;       are generated by the assembler.
; ============================================================================

; ----------------------------------------------------------------------------
; SECTION 1: Valid Macro Declarations (Pre-processor will process successfully)
; ----------------------------------------------------------------------------

mcro MY_GOOD_MAC
    add $1, $2, $3
    sub $4, $5, $6
mcroend

; Calling the valid macro (this will expand correctly in the .am file)
MY_GOOD_MAC

; ----------------------------------------------------------------------------
; SECTION 2: First Pass Syntax & Semantic Errors
; (Pre-processor ignores these, but First Pass MUST fail here)
; ----------------------------------------------------------------------------

; Error 1: Invalid opcode name (does not exist in the 2026 instruction set)
invalidopcode $10, $11, $12

; Error 2: Register index out of bounds (registers must be between $0 and $31)
add $35, $1, $2

; Error 3: Duplicate label definition (Label 'MULTIDEF' defined twice)
MULTIDEF: move $1, $2
MULTIDEF: or $3, $4, $5

; Error 4: Extraneous or misplaced comma in instruction operands
sub $4, , $5, $6

; Error 5: Data directive value out of range 
; Valid range is -128 to 127. 500 is invalid.
ERR_DATA: .db 500
